const data = {
    product : [
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/naan.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'biriyani',
        },
        {
            name : "biriyani",
            slug: "veg-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/rice.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'kebab',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/naan.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'naan',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/snacks.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'indian curry',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img1.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'dosa',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'drinks',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'indian thaali',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'vegetrian cuisine',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'sweets',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'desserts',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'mutton dishes',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'biriyani',
        },
        {
            name : "biriyani",
            slug: "chicken-menu",
            catergory: "veg",
            price: "54",
            image: "/assets/img4.jpeg",
            countInStock: "20",
            rate: "4.5",
            food_category: '/assets/meat.png',
            category_name: 'pulavs',
        },
    ]
}
export default data;